ChomikUJ/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = \
    [
        url(r'^admin/', admin.site.urls),
        url(r'^', include('MainPage.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainPage/urls.py
from django.conf.urls import url
from django.contrib import admin

from MainPage import views

app_name = 'MainPage'

urlpatterns = \
[
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^$', views.login_user, name='login'),
    url(r'^editprofile/$', views.edit_profile, name='editprofile'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^home/$', views.home, name='home'),
    url(r'^showprofiles/(?P<profile_id>[0-9]+)/$', views.show_profile, name='show_profile'),
    url(r'^showprofiles/$', views.show_profile_list, name='show_profile_list'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^follows/$', views.follows, name='follows'),
    url(r'^files/$', views.manage_files, name='manage_files'),
    url(r'^comments/$', views.manage_comments, name='manage_comments')

]

MainPage/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.contrib.auth.models import User
from datetime import date

fs = FileSystemStorage(location='/media/files')


def _upload_path(instance, filename):
    return instance.get_upload_path(filename)


class Profile(models.Model):
    id = models.IntegerField(primary_key=True)
    auth = models.ForeignKey(User, null=True)
    first_name = models.CharField(max_length=128, default="first name")
    last_name = models.CharField(max_length=128, default="last name")
    age = models.PositiveIntegerField(null=True)
    city = models.CharField(max_length=128, null=True)
    photo = models.ImageField(null=True)
    email = models.CharField(max_length=1024, default='email')
    used_transfer = models.FloatField(default=0)

    def __str__(self):
        return str(self.first_name + " " + self.last_name)


class Relationship(models.Model):
    class Meta:
        unique_together = ('user1_id', 'user2_id')

    user1_id = models.ForeignKey(Profile, related_name="user_one")
    user2_id = models.ForeignKey(Profile, related_name="user_two")

    def __str__(self):
        return self.id


class Posts(models.Model):
    profile = models.ForeignKey(Profile, null=True, related_name="profile")
    timeline_id = models.IntegerField(default=0)
    text = models.CharField(max_length=3000)
    class Meta:
        verbose_name_plural = "Posts"


class Files(models.Model):
    file = models.FileField(upload_to=_upload_path)
    name = models.TextField(default="name")
    user = models.ForeignKey(Profile, related_name="user")
    date = models.DateField(default=date.today)
    size = models.FloatField(default=0)

    class Meta:
        verbose_name_plural = "Files"

    def get_upload_path(self, filename):
        return "static/uploads/" + str(self.user.id) + "/" + filename

MainPage/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Posts


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'age', 'city', 'photo','email']


class TimelineForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['text']

MainPage/views.py
import os

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.urls import reverse
from .models import Profile, Posts, Relationship, Files
from .forms import UserForm, ProfileForm, TimelineForm
from celery.schedules import crontab
from celery.task import periodic_task


@periodic_task(run_every=crontab(hour=21, minute=43, day_of_week=3))
def every_monday_morning():
    profiles = Profile.objects.all()
    for profile in profiles:
        profile.used_transfer = 0
        profile.save()


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    return render(request, 'MainPage/login.html', {"form": form})


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                url = reverse('MainPage:editprofile', args=(),
                              kwargs={})
                return HttpResponseRedirect(url)
    context = {
        "form": form,
    }
    return render(request, 'mainpage/register.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                try:
                    get_object_or_404(Profile, auth=request.user)
                except:
                    url = reverse('MainPage:editprofile', args=(),
                                  kwargs={})
                    return HttpResponseRedirect(url)
                url = reverse('MainPage:home', args=(),
                              kwargs={})
                return HttpResponseRedirect(url)
            else:
                return render(request, 'MainPage/login.html',
                              {'error_message': 'Konto nieaktywne. Skontaktuj się z adminem.'})
        else:
            return render(request, 'MainPage/login.html', {'error_message': 'Invalid login'})
    return render(request, 'MainPage/login.html')


def edit_profile(request):
    try:
        profile = Profile.objects.get(auth=request.user)
        url = reverse('MainPage:home', args=(),
                      kwargs={})
        return HttpResponseRedirect(url)
    except:
        print('exception')

    if request.method == 'POST':
        form = ProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.auth = request.user
            profile.first_name = form.cleaned_data['first_name']
            profile.last_name = form.cleaned_data['last_name']
            profile.photo = request.FILES['photo']
            profile.age = form.cleaned_data['age']
            profile.city = form.cleaned_data['city']
            profile.email = form.cleaned_data['email']
            profile.save()
            url = reverse('MainPage:home', args=(),
                          kwargs={})
            return HttpResponseRedirect(url)

        error = {
            "error_message": "Uzupełnij wszystkie pola!",
        }
        return render(request, 'mainpage/editprofile.html', error)
    return render(request, 'mainpage/editprofile.html')


def home(request):
    if not request.user.is_authenticated():
        return render(request, "MainPage/login.html")
    if request.user is not None:
        if request.user.is_active:
            try:
                get_object_or_404(Profile, auth=request.user)
            except:
                url = reverse('MainPage:editprofile', args=(),
                              kwargs={})
                return HttpResponseRedirect(url)
    if request.method == 'POST':
        form = TimelineForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.profile = Profile.objects.get(auth=request.user)
            post.timeline_id = request.user.id
            post.text = form.cleaned_data['text']
            post.save()

    if request.method == 'POST' and not TimelineForm(request.POST or None).is_valid():
        requestFile = request.FILES['file']
        profile = get_object_or_404(Profile, auth=request.user)
        filesSize = profile.used_transfer
        if filesSize + requestFile.size >= 2000000000:
            profile = get_object_or_404(Profile, auth=request.user)
            timeline = Posts.objects.filter(timeline_id=request.user.id)
            files = Files.objects.filter(user=profile)
            return render(request, 'MainPage/home2.html', {'profile': profile, 'timeline': timeline, 'files': files,
                                                           'message': "Nie masz miejsca na dysku!"})
        files = Files()
        files.file = requestFile
        files.name = requestFile.name
        files.size = requestFile.size
        files.user = get_object_or_404(Profile, auth=request.user)
        profile.used_transfer += files.size
        profile.save()
        files.save()

    profile = get_object_or_404(Profile, auth=request.user)
    timeline = Posts.objects.filter(timeline_id=request.user.id)
    files = Files.objects.filter(user=profile)

    return render(request, 'MainPage/home2.html', {'profile': profile, 'timeline': timeline, 'files': files})


def show_profile(request, profile_id):
    if not request.user.is_authenticated():
        return render(request, "MainPage/login.html")
    if request.method == 'POST':
        form = TimelineForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.profile = Profile.objects.get(auth=request.user)
            post.timeline_id = profile_id
            post.text = form.cleaned_data['text']
            post.save()
    profile = Profile.objects.get(auth_id=profile_id)
    timeline = Posts.objects.filter(timeline_id=profile_id)
    files = Files.objects.filter(user=profile)
    return render(request, 'MainPage/profile.html', {'profile': profile, 'timeline': timeline, 'files': files})


def settings(request):
    if not request.user.is_authenticated():
        return render(request, "MainPage/login.html")
    if request.method == 'POST':
        try:
            first_name = request.POST['first_name']
        except:
            first_name = None
        try:
            last_name = request.POST['last_name']
        except:
            last_name = None
        try:
            photo = request.FILES['photo']
        except:
            photo = None
        try:
            age = request.POST['age']
        except:
            age = None
        try:
            email = request.POST['email']
        except:
            email = None
        try:
            city = request.POST['city']
        except:
            city = None
        profile = Profile.objects.get(auth=request.user)
        if first_name != "":
            profile.first_name = first_name
            profile.save()
        if last_name != "":
            profile.last_name = last_name
            profile.save()
        if photo is not None:
            profile.photo = photo
            profile.save()
        if age != "":
            profile.age = age
            profile.save()
        if email != "":
            profile.email = email
            profile.save()
        if city != "":
            profile.city = city
            profile.save()

        profile.save()
        url = reverse('MainPage:home', args=(),
                      kwargs={})
        return HttpResponseRedirect(url)

    return render(request, "MainPage/settings.html")


def show_profile_list(request):
    if not request.user.is_authenticated():
        return render(request, "MainPage/login.html")
    profiles = Profile.objects.all()
    if request.method == 'POST':
        query = request.POST.get('q')
        if query:
            query_list = query.split()
            if len(query_list)==2:
                profiles = Profile.objects.filter(first_name=query_list[0],last_name=query_list[1])
                return render(request, 'MainPage/users.html', {'profiles': profiles})
        if request.POST.get('button'):
            user_id = request.POST.get('button')
            profile1 = Profile.objects.get(auth=request.user)
            profile2 = Profile.objects.get(id=user_id)
            relationship = Relationship(user1_id=profile1, user2_id=profile2)
            relationship.save()
            return render(request, 'MainPage/users.html', {'profiles': profiles, 'user': user_id})
    return render(request, 'MainPage/users.html', {'profiles': profiles})


def follows(request):
    if not request.user.is_authenticated():
        return render(request, "MainPage/login.html")
    if request.method == 'POST':
        user_id = request.POST.get('button')
        profile1 = Profile.objects.get(auth=request.user)
        profile2 = Profile.objects.get(id=user_id)
        relationship = Relationship.objects.get(user1_id=profile1, user2_id=profile2)
        relationship.delete()
    my_profile = Profile.objects.get(auth=request.user)
    relationships = Relationship.objects.all()
    profiles = []
    for relationship in relationships:
        if relationship.user1_id == my_profile:
            profiles.append(relationship.user2_id)
    return render(request, 'MainPage/follows.html', {'profiles': profiles})


def manage_files(request):
    if not request.user.is_authenticated():
        return render(request, "MainPage/login.html")

MainPage/templates/MainPage/follows.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Chomik UJ</title>
  <meta charset="utf-8">
    {% load staticfiles %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'MainPage/home2.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'MainPage/users.css' %}">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="{%  url 'MainPage:home' %}">PROFIL</a></li>
            <li><a href="{% url 'MainPage:settings' %}">USTAWIENIA</a></li>
            <li><a href="{%  url 'MainPage:show_profile_list' %}">UZYTKOWNICY</a></li>
            <li><a href="{%  url 'MainPage:follows' %}">OBSERWOWANI</a></li>
            <li><a href="{%  url 'MainPage:manage_files' %}">ZARZĄDZAJ PLIKAMI</a></li>
            <li><a href="{%  url 'MainPage:manage_comments' %}">KOMENTARZE</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
             <a class="navbar-brand" href="{% url 'MainPage:logout_user' %}">Wyloguj</a>
        </ul>
    </div>
</nav>
<div class="jumbotron text-center">
  <h1>Chomik UJ</h1>
   <p>Wirtualny dysk</p>
</div>
{% for profile in profiles %}
<div class="container">
<div class="row">
    <div class="col-md-2"></div>
    <div class="panel panel-primary col-md-8">
      <div class="panel-heading"><h3>{{ profile.first_name }} {{ profile.last_name }}</h3></div>
      <div class="panel-body">
        <div class="col-md-4"><a href = "{% url 'MainPage:show_profile' profile.id %}"><img class="img-circle img-responsive" alt="Avatar" src="{{ profile.photo.url }}"></a></div>
           <div class="col-md-6">
             <div class="row"><label for="music">Imię:  </label> <p id="name" class="answer">{{ profile.first_name }}</p></div><br>
               <div class="row"><label for="age">Nazwisko: </label> <p id="surname" class="answer">{{ profile.last_name }}</p></div><br>
               <form action="" method="post">
                   {% csrf_token %}
                    <button name=button value="{{profile.id}}" type="submit" formmethod="post">Unfollow</button>
                </form>
               {% csrf_token %}

           </div>
           </div>
    </div>
        <div class="col-md-2"></div>
    </div></div>
{% endfor %}
</body>

MainPage/templates/MainPage/home2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Chomik UJ</title>
    <meta charset="utf-8">
        {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'MainPage/home2.css' %}"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <SCRIPT type="text/javascript">
    function ValidateFileUpload()
    {
        var fuData = document.getElementById('exampleInputFile');
        var FileUploadPath = fuData.value;
        if (FileUploadPath == '')
        {
            alert("Załącz plik!");
            return false;
        }

        var oFile = document.getElementById("exampleInputFile").files[0];

            if (oFile.size > 500000000) // 2 mb for bytes.
            {
                alert("Rozmiar pliku nie może przekraczać 0.5GB!");
                return false;
            }
    }
</SCRIPT>
        <script>
function sortList() {
  var list, i, switching, b, shouldSwitch;
  list = document.getElementById("id01");
  switching = true;
  while (switching) {

    switching = false;
    b = list.getElementsByTagName("LI");

    for (i = 0; i < (b.length - 1); i++) {

      shouldSwitch = false;

      if (b[i].innerHTML.toLowerCase() > b[i + 1].innerHTML.toLowerCase()) {

        shouldSwitch= true;
        break;
      }
    }
    if (shouldSwitch) {

      b[i].parentNode.insertBefore(b[i + 1], b[i]);
      switching = true;
    }
  }
}
</script>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default" role="navigation">


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="{%  url 'MainPage:home' %}">PROFIL</a></li>
            <li><a href="{% url 'MainPage:settings' %}">USTAWIENIA</a></li>
            <li><a href="{%  url 'MainPage:show_profile_list' %}">UZYTKOWNICY</a></li>
            <li><a href="{%  url 'MainPage:follows' %}">OBSERWOWANI</a></li>
            <li><a href="{%  url 'MainPage:manage_files' %}">ZARZĄDZAJ PLIKAMI</a></li>
            <li><a href="{%  url 'MainPage:manage_comments' %}">KOMENTARZE</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
             <a class="navbar-brand" href="{% url 'MainPage:logout_user' %}">Wyloguj</a>
        </ul>
    </div>
</nav>
<div class="jumbotron text-center">
  <h1>Chomik UJ</h1>
  <p>Wirtualny dysk</p>
</div>
<div class="container text-center" style="margin-top:3%;">
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <img src="{{ profile.photo.url }}" class="img-circle img-responsive" alt="Avatar">
      </div>
         <div class="panel panel-default"><h3><strong>{{ profile.first_name }} {{ profile.last_name }}</strong></h3></div>
         <div class="well text-left">
      <p><label>Wiek: </label> {{ profile.age }}</p>
      <p><label>Miasto: </label>  {{ profile.city }}</p>
      <p><label>Mail: </label> {{ profile.email }} </p></div>
    </div>

    <div class="col-sm-7">
        {% if message %}
        <h3 style="color: red">{{message}}</h3>
        {% endif %}
      <div class="row">
        <div class="col-sm-12">
            <form class="form-horizontal" name = "MyForm" role="form" action="" onsubmit="return ValidateFileUpload();" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
			    <div class="form-group row" style="display:inline;">
				    <div >Udostępnij plik</div>
				    <input type="file" id="exampleInputFile" onchange="return ValidateFileUpload()" name="file">
                    <button type="submit" class="btn btn-success">Wrzucaj!</button>
			  	</div><br>
        </form>
         <div class="well">
        <p>
          <a href="https://www.facebook.com/"><span class="label label-primary"><i class="fa fa-facebook-square"></i>Facebook</span></a>
          <a href="https://www.instagram.com/"><span class="label label-success"><i class="fa fa-instagram"></i>Instagram</span></a>
          <a href="https://www.youtube.com/?hl=pl&gl=PL"><span class="label label-danger"><i class="fa fa-youtube"></i>YouTube</span></a>
        </p>
      </div>
          <div class="panel panel-default text-left" >
          <div class="panel-heading">Dodaj post</div>
            <div class="panel-body">
               <form role="form" action="" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" type="text" name="text" placeholder="Your comments" rows="5"> </textarea>
                    </div>
                   <button type="submit" class="btn btn-success" style="background-color: #0000ff;border-color: #0000ff;">Submit</button>

                  <!--  <button class="btn btn-default" onclick="myFunction()">Dodaj</button>-->
              </form>
            </div>
          </div>
        </div>

      </div>
      <div class="row">
<div class="col-sm-12">
<div class="panel panel-default "><h3>Posty użytkownika {{ profile.first_name }}</h3></div>
</div>
</div>
       {%  for field in timeline %}
      <div class="row">
        <div class="col-sm-2">
          <div class="thumbnail">
          <img class="img-responsive user-photo" src="{{ field.profile.photo.url }}" >
          </div>
          </div>
        <div class="col-sm-10">
          <div class="well" style="padding-top: 0; padding-left: 0; padding-right: 0;">
              <div class="panel panel-default">{{ field.profile.first_name }} {{ field.profile.last_name }}</div>
            <p>{{ field.text }}</p>
          </div>
        </div>
      </div>
        {% endfor %}
    </div>
    <div class="col-sm-2 well">
      <div class="thumbnail">
        <p>Moje pliki</p>
         <ul id="id01">
             {% for file in files %}
             <li style="word-wrap: break-word"><a href="{{file.file.url}}" download>{{file.name}}</a></li>
             {% endfor %}
        </ul>
      </div>
        <p>Sortuj alfabetycznie</p>
        <button onclick="sortList()">Sortuj</button>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>Back <a href="https://www.w3schools.com" title="Visit w3schools"></a></p>
</footer>

<script>
$(document).ready(function(){
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
    if (this.hash !== "") {

      event.preventDefault();

      var hash = this.hash;
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){

        window.location.hash = hash;
      });
    }
  });

  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})
</script>

</body>
</html>

MainPage/templates/MainPage/manage_comments.html
<!DOCTYPE html>
<html lang="en" xmlns:width="http://www.w3.org/1999/xhtml">
<head>
  <title>Chomik UJ</title>
  <meta charset="utf-8">
    {% load staticfiles %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'MainPage/home2.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'MainPage/users.css' %}">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="{%  url 'MainPage:home' %}">PROFIL</a></li>
            <li><a href="{% url 'MainPage:settings' %}">USTAWIENIA</a></li>
            <li><a href="{%  url 'MainPage:show_profile_list' %}">UZYTKOWNICY</a></li>
            <li><a href="{%  url 'MainPage:follows' %}">OBSERWOWANI</a></li>
            <li><a href="{%  url 'MainPage:manage_files' %}">ZARZĄDZAJ PLIKAMI</a></li>
            <li><a href="{%  url 'MainPage:manage_comments' %}">KOMENTARZE</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
             <a class="navbar-brand" href="{% url 'MainPage:logout_user' %}">Wyloguj</a>
        </ul>
    </div>
</nav>
<div class="jumbotron text-center">
  <h1>Chomik UJ</h1>
   <p>Moja wirtualna wizytówka</p>
</div>
       {%  for field in timeline %}
      <div class="row">
        <div class="col-sm-2">
          <div class="thumbnail">
          <img class="img-responsive user-photo" src="{{ field.profile.photo.url }}" >
          </div>
          </div>
        <div class="col-sm-10">
          <div class="well" style="padding-top: 0; padding-left: 0; padding-right: 0;">
              <div class="panel panel-default">{{ field.profile.first_name }} {{ field.profile.last_name }}</div>
            <p>{{ field.text }}</p>
                                       <form action="" method="post">
                   {% csrf_token %}
                    <button name=button value="{{field.id}}" type="submit" formmethod="post">Usuń</button>
                </form>
          </div>
        </div>
      </div>
        {% endfor %}

</body>

MainPage/templates/MainPage/users.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Chomik UJ</title>
  <meta charset="utf-8">
    {% load staticfiles %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'MainPage/home2.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'MainPage/users.css' %}">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="{%  url 'MainPage:home' %}">PROFIL</a></li>
            <li><a href="{% url 'MainPage:settings' %}">USTAWIENIA</a></li>
            <li><a href="{%  url 'MainPage:show_profile_list' %}">UZYTKOWNICY</a></li>
            <li><a href="{%  url 'MainPage:follows' %}">OBSERWOWANI</a></li>
            <li><a href="{%  url 'MainPage:manage_files' %}">ZARZĄDZAJ PLIKAMI</a></li>
            <li><a href="{%  url 'MainPage:manage_comments' %}">KOMENTARZE</a></li>
            <li><a class="navbar-brand" href="{% url 'MainPage:logout_user' %}">Wyloguj</a></li>
        </ul>
               <form class="navbar-form" role="search">
            {% csrf_token %}
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Szukaj użytkownika" name="q">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit" formmethod="post" ><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
    </div>
</nav>
<div class="jumbotron text-center">
  <h1>Chomik UJ</h1>
   <p>Wirtualny dysk</p>
</div>
{% for profile in profiles %}
<div class="container"> 
<div class="row">
    <div class="col-md-2"></div>
    <div class="panel panel-primary col-md-8">
      <div class="panel-heading"><h3>{{ profile.first_name }} {{ profile.last_name }}</h3></div>
      <div class="panel-body">
        <div class="col-md-4"><a href = "{% url 'MainPage:show_profile' profile.id %}"><img class="img-circle img-responsive" alt="Avatar" src="{{ profile.photo.url }}"></a></div>
           <div class="col-md-6">
             <div class="row"><label for="music">Imię:  </label> <p id="name" class="answer">{{ profile.first_name }}</p></div><br>
               <div class="row"><label for="age">Nazwisko: </label> <p id="surname" class="answer">{{ profile.last_name }}</p></div><br>
               <form action="" method="post">
                   {% csrf_token %}
                    <button name=button value="{{profile.id}}" type="submit" formmethod="post">Follow</button>
                </form>
               {% csrf_token %}

           </div>
           </div>
    </div>
        <div class="col-md-2"></div>
    </div></div>
{% endfor %}
</body>